on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: linter

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.x"
    - uses: golangci/golangci-lint-action@v8
      with:
        version: "v2.1"
